import type { Metadata } from "next";
import { Inter } from "next/font/google";
import MainProvider from "@/src/1_app/MainProvider";
import Navbar from "@/src/3_widget/Navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.svg" sizes="any" />
      </head>
      <body className={inter.className}>
        <MainProvider>
        <Navbar/>
          {children}
          </MainProvider>
        </body>
    </html>
  );
}
